version: "3.0"
services:
  elasticsearch:
    container_name: es-practice-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    networks:
      - es-practice-net
    ports:
      - "9200:9200"
  kibana:
    container_name: kb-practice-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-practice-container:9200
    networks:
      - es-practice-net
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
networks:
  es-practice-net:
    driver: bridge
